name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwayland-dev \
          libxkbcommon-dev \
          wayland-protocols \
          extra-cmake-modules \
          libdecor-0-dev \
          libegl1-mesa-dev \
          xorg-dev \
          lcov

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -Wno-dev

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test with Coverage
      run: |
        cd ${{github.workspace}}/build
        ./connect4_test
        lcov --capture --directory . --output-file coverage.info --ignore-errors inconsistent,mismatch
        lcov --remove coverage.info '/usr/*' '*/tests/*' '*/googletest/*' '*/build/_deps/plog-src/include/plog/*' --output-file coverage.info --ignore-errors inconsistent,mismatch
        
        # Extract coverage percentage and check threshold
        COVERAGE_PERCENT=$(lcov --summary coverage.info | grep "lines" | cut -d '|' -f 2 | cut -d '%' -f 1 | tr -d '[:space:]')
        echo "Coverage: $COVERAGE_PERCENT%"
        
        if (( $(echo "$COVERAGE_PERCENT < 75" | bc -l) )); then
          echo "Code coverage is below 75% (actual: $COVERAGE_PERCENT%)"
          exit 1
        fi

    - name: Generate Coverage Report
      run: |
        cd ${{github.workspace}}/build
        genhtml coverage.info --output-directory coverage_report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ${{github.workspace}}/build/coverage_report
